[package]
name = "blur-image"
version = "0.1.0"
authors = ["Tamás Táncos <tamas.tancos@emarsys.com>"]
edition = "2018"

[dependencies]
fastblur = "0.1.0"
image = "0.20.0"
base64 = "0.9.3"
mime_guess = "1.8.6"
mime = "0.3.12"
clap = "2.32.0"